# Generated by Django 4.0.5 on 2022-08-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='frequency',
            field=models.CharField(max_length=50),
        ),
    ]
