# Generated by Django 4.0.5 on 2022-08-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_appointment_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='year',
            new_name='date',
        ),
    ]
