# Generated by Django 4.0.5 on 2022-08-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='service',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='static/image'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
